In [21]:
print("Naresh Kumar Bachu")

Naresh Kumar Bachu


In [7]:
import numpy as np
a = np.array([[7,3],[1,2]])
b = np.array([20,9])
c = np.linalg.solve(a,b)
print(c)

[1.18181818 3.90909091]


In [16]:
import numpy as np
a = np.array([[10,-5],[4,2]])
b = np.array([35,10])
c = np.linalg.solve(a,b)
print(c)

[ 3. -1.]


In [11]:
import numpy as np
a = np.array([[20,-7],[5,6]])
b = np.array([55,40])
c = np.linalg.solve(a,b)
print(c)

[3.93548387 3.38709677]


In [14]:
import numpy as np
a = np.array([[8,3,-2],[2,-1,5],[-7,5,-1]])
b = np.array([27,18,6])
c = np.linalg.solve(a,b)
print(c)

[2.34343434 5.22222222 3.70707071]


In [15]:
import numpy as np
a = np.array([[8,2,-7],[3,-1,5],[-2,5,-1]])
b = np.array([27,18,6])
c = np.linalg.solve(a,b)
print(c)

[4.12121212 3.2020202  1.76767677]


In [18]:
import numpy as np
a = np.array([[7,3],[1,2]])
b = np.array([20,9])
c = np.linalg.inv(a)
d = np.dot(b,c)
print(d)

[2.81818182 0.27272727]


In [19]:
import numpy as np
a = np.array([[3,7],[2,1]])
b = np.array([9,20])
c = np.linalg.inv(a)
d = np.dot(b,c)
print(d)

[2.81818182 0.27272727]


In [32]:
import numpy as np
a = np.array([[2, 1, 4, 3], [1, -2, 0, 3], [3, 2, -1, 1], [0, 4, 0, -5]])
b = np.array([5, 3, -1, -3])
c = np.linalg.inv(a)
d = np.dot(b, c)
print(d)

[-0.33333333  6.66666667 -0.33333333  4.33333333]


In [36]:
import numpy as np
a = np.array([[-3, -7, 8, 0], [1, 3, 10, 0], [-4, -2, 2, 0], [0, 6, 5, -10]])
b = np.array([40, 15, 5, 20])
c = np.linalg.inv(a)
d = np.dot(b, c)
print(d)

[ 0.18918919  3.21621622 -9.33783784 -2.        ]


In [37]:
import numpy as np
a = np.array([[8, 1, 1], [1, 2, 1], [1, 1, -1600]])
b = np.array([0, 0, 0])
c = np.linalg.inv(a)
d = np.dot(b, c)
print(d)

[0. 0. 0.]
